from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
items=[
('NHS','Clinical information','NHS: ADHD in adults','https://www.nhs.uk/conditions/adhd-adults/','Start with an overview of adult ADHD, assessment and treatment.','Official NHS patient information.'),
('MEDICATION','Provider explanation','ADHD Direct: Is ADHD Medication Even Real?','https://adhddirect.co.uk/blog/is-adhd-medication-even-real-lets-talk-about-it/','Prepare questions about medication and common misconceptions.','A clinic-authored explainer; individual treatment decisions belong with your prescriber.'),
('SHARED','Provider explanation','ADHD Direct: shared care explained','https://adhddirect.co.uk/blog/shared-care-explained/','Understand the provider’s explanation of why a GP might decline shared care.','A private provider’s account, not a binding statement of the law or your local commissioning policy. Use alongside the transfer and handover route.'),
('EMC','Product information','Electronic medicines compendium (emc)','https://www.medicines.org.uk/emc/','Find the patient leaflet and prescribing information for the exact medicine, strength and formulation.','Product-specific information. Bring questions about ingredients, side effects or instructions to your pharmacist or prescriber.'),
('PMDD','Provider explanation','ADHD Direct: ADHD and PMDD','https://adhddirect.co.uk/blog/adhd-and-pmdd-whats-the-link/','Find a starting point for discussing symptoms that change around the menstrual cycle.','Clinic-authored discussion. The link supplied under this title pointed to a different article; this is the matching public page.'),
('PMDD-NHS','Clinical information','NHS: PMDD','https://www.nhs.uk/conditions/pmdd-premenstrual-dysphoric-disorder/','Read the NHS overview of PMDD and routes to assessment and support.','Official patient information to accompany the provider’s ADHD/PMDD article.'),
('DIRECT','Provider website','ADHD Direct','https://adhddirect.co.uk/','Find the clinic’s service information, resources and contact routes.','Commercial clinical provider. Check current fees, terms and prescribing arrangements directly.'),
('HOWTO','Practical videos','How to ADHD — Jessica McCabe','https://howtoadhd.com/','Explore videos about everyday ADHD challenges, including home, work and relationships.','Creator-led educational content. The official site links its YouTube videos and playlists.'),
('SCOTLAND','Peer support','Scottish ADHD Coalition','https://www.scottishadhdcoalition.org/','Find ADHD support organisations and local groups in Scotland.','Scottish support network; group availability and remit vary.'),
('AADD','Peer support','AADD-UK','https://aadduk.org/','Explore adult ADHD peer resources and UK support-group information.','An adult ADHD community resource; check the date of individual pages and current group details.'),
('UNDERSTOOD','Practical information','Understood','https://www.understood.org/','Explore practical explanations and strategies for learning, attention and workplace challenges.','US-based resource. Its healthcare, employment and education rules are not UK rules.'),
('ATW','Government scheme','Access to Work','https://www.gov.uk/access-to-work','Check the support available for disability-related difficulties at work and how to apply.','Official guidance for England, Scotland and Wales. Eligibility and awarded support are assessed; Northern Ireland has a separate route.'),
('DRIVING','Government guidance','ADHD and driving — GOV.UK','https://www.gov.uk/adhd-and-driving','Check the current DVLA notification guidance rather than relying on a social-media answer.','Official Great Britain guidance; use the linked rules for your licence category and circumstances.'),
('ADD','Magazine / educational content','ADDitude','https://www.additudemag.com/','Browse articles, expert discussions and practical ADHD resources.','US-based commercial publication with advertising and paid material. Publication does not make every article a clinical guideline.'),
('BARKLEY','Book','Taking Charge of Adult ADHD — Russell A. Barkley, with Christine M. Benton','https://www.guilford.com/books/Taking-Charge-of-Adult-ADHD/Russell-Barkley/9781462546855','Explore a structured reference on adult ADHD, treatment questions and practical strategies.','Second edition verified on the publisher’s page; paperback ISBN 9781462546855. A listing check is not a full review of the book.'),
('HALLOWELL','Book','Driven to Distraction — Edward M. Hallowell and John J. Ratey','https://drhallowell.com/read/books-by-ned/','Explore an established ADHD book through the author’s bibliography.','Book listing checked on the author’s site. Check edition and date when discussing treatment information.'),
('MATE','Book / author perspective','Scattered Minds — Gabor Maté','https://drgabormate.com/book/scattered-minds/','Explore the author’s perspective on attention difficulties and lived experience.','Listed in the supplied resource recommendations. An author’s explanatory framework is not established proof of ADHD causation; compare claims with the genetics and evidence routes.'),
('HABITS','General self-help book','Atomic Habits — James Clear','https://jamesclear.com/atomic-habits','Explore approaches to building routines and changing the surrounding environment.','General habit advice, not an ADHD-specific clinical reference or evidence that disability can be overcome by willpower.'),
('POD-ADULT','Podcast','The ADHD Adults Podcast','https://theadhdadults.uk/','Listen to UK adult ADHD discussion, information and personal experiences.','Podcast format; individual episodes mix explanation and lived experience.'),
('POD-ADD','Webinars / podcast','ADDitude ADHD Experts Podcast','https://www.additudemag.com/adhd-expert-webinars-index/','Find topic-specific expert discussions, episodes and accompanying slides.','Publisher’s indexed listing verified through search; direct page access was blocked during this check. Check each speaker, date and any sponsorship.'),
('FOREST','Focus app','Forest','https://www.forestapp.cc/','Try a visual focus timer for a short task.','Optional commercial tool; check current platform, pricing and accessibility before installing.'),
('TODOIST','Task app','Todoist','https://www.todoist.com/','Keep tasks and reminders in one place.','Optional organisation tool; start with a small list rather than an elaborate system.'),
('SIMPLEMIND','Mind-mapping app','SimpleMind','https://simplemind.eu/','Arrange ideas visually when a linear list is difficult to use.','Optional commercial tool; check your device, export options and accessibility.'),
('PRODUCTIVE','Habit app','Productive','https://productiveapp.io/','Try reminders and a simple record of a routine.','Optional commercial tool. Tracking should reduce effort rather than become another obligation.'),
]
sources_path=root/'guidebook/content/sources.json'
sources=json.loads(sources_path.read_text())
sources=[s for s in sources if not s['id'].startswith('RES-')]
for key,kind,title,url,purpose,note in items:
 sources.append(dict(id='RES-'+key,type=kind,short=title,citation=title,url=url,access='Originating public page checked' if key!='POD-ADD' else 'Publisher listing via search; direct fetch blocked',checked='2026-10-07',note='Directory entry and intended use verified; not an independent review of all content. '+note))
sources_path.write_text(json.dumps(sources,ensure_ascii=False,indent=2)+'\n')
lines=['---','id: adhd-resources','title: ADHD resources: find what you need','short: ADHD resources','route: /about/adhd-resources/','entrance: about','priority: 4','summary: Purpose-labelled links for medication questions, shared care, peer support, work, books, podcasts and practical tools.','status: drafted','reviewed: 2026-10-07','next_action: appointment-preparation','next_related: transfer-handover','next_deeper: evidence-method','---','@layer 1 Choose your purpose','You do not need to read everything. Pick the question you have today, open one resource, and keep anything useful with your appointment notes.','', 'This directory brings together public resources from ADHD Direct’s recommendations, with additional official links where they help. Every entry explains its purpose and what kind of source it is. No personal clinical correspondence is reproduced here.','', '- **Medication or shared care:** start with the NHS overview, the clinic explainers and the exact product leaflet.','- **Day-to-day support:** try one practical video, support group or simple tool.','- **Work:** check the official Access to Work route.','- **Longer reading or listening:** choose a book or podcast by topic, format and energy available.','','@layer 2 Medication, care and related questions']
for i,(key,kind,title,url,purpose,note) in enumerate(items):
 if i==7: lines+=['','@layer 3 Everyday support and work']
 if i==14: lines+=['','@layer 4 Books: know what you are choosing','Book links identify the title and author. They are not “must-buy” endorsements or claims that the whole text has been independently reviewed. Check library availability, an excerpt or an accessible format before buying.']
 if i==18: lines+=['','@layer 5 Podcasts and practical tools','Apps support a task or routine; they are not treatments in themselves. Pricing, permissions and accessibility can change. Choose a format that works for you.']
 lines+=['','## '+title,'**Useful for:** '+purpose,'','**Source type:** '+kind+'. '+note,'','[Open this resource]('+url+') · {RES-'+key+'}']
lines+=['','@layer 6 Use a resource in your next appointment','Turn what you read into one concrete question: what needs deciding, what information is missing, and who will do the next step? Use [[appointment-preparation]], [[transfer-handover]] and [[evidence-method]].','','@uncertainty','Links and bibliographic details were checked on 7 October 2026. A working link does not establish the quality of every statement on an external site. NHS and government sources, provider explanations, personal experience and commercial resources have different roles. New recommendations need an identifiable publisher or listing before they are added.']
(root/'guidebook/content/pages/54-resources.md').write_text('\n'.join(lines)+'\n')
for filename in ['10-hub-treatment.md','23-transfer.md','53-appointment.md']:
 p=root/'guidebook/content/pages'/filename
 text=p.read_text()
 if '[[adhd-resources]]' not in text: p.write_text(text+('\n' if '@layer 6 ' in text else '\n@layer 6 Useful resources\n')+'Find purpose-labelled external reading, videos, support groups and tools in [[adhd-resources]].\n')
p=root/'site/index.html';text=p.read_text();needle="  <a href='/accountability/uk/'>UK mental health care accountability</a>"
if 'ADHD resources by purpose' not in text: text=text.replace(needle,"  <a href='/guide/static/about/adhd-resources/'>ADHD resources by purpose</a>\n"+needle)
p.write_text(text)
print('Prepared',len(items),'purpose-labelled resources using public URLs only.')
