#!/usr/bin/env python3
"""Build the sourced accountability hub and accessible case register."""
from pathlib import Path
import csv, html, json
R=Path(__file__).resolve().parents[1]; S=R/'site'
def a(url,text): return f'<a href="{html.escape(url)}">{html.escape(text)}</a>'
PHSO='https://www.ombudsman.org.uk/publications/missed-opportunities-what-lessons-can-be-learned-failings-north-essex/our-investigations'
LAMP='https://lampardinquiry.org.uk/family-and-friends-evidence-directory/matthew-leahy/'
STATEMENT='https://lampardinquiry.org.uk/wp-content/uploads/2024/09/Melanie-Leahys-Commemorative-Statement.pdf'
HSSIB='https://www.hssib.org.uk/patient-safety-investigations/mental-health-inpatient-settings/fifth-investigation-report/'
RECS='https://www.hssib.org.uk/patient-safety-investigations/recommendations-but-no-action-improving-the-effectiveness-of-quality-and-safety-recommendations-in-healthcare/report/'
CQC='https://www.cqc.org.uk/publications/monitoring-mental-health-act/2024-2025'
REGS='https://www.cqc.org.uk/guidance-regulation/regulations-service-providers-and-managers'
COMPLAINT='https://www.england.nhs.uk/contact-us/feedback-and-complaints/complaint/'
BETH='https://assets.publishing.service.gov.uk/media/5dc58c73e5274a4eb55909a0/Serious_incident_investigation_report_-_Secretary_of_State_case_review_into_Beth.pdf'
def case(slug,name,age,gender,context,outcome,incident,finding,response,url,kind='Coroner report',gap='The reviewed source does not establish whether every corrective action was completed. This is an implementation question, not a finding that no action occurred.'):
 return dict(id=slug,name=name,age=age,gender=gender,context=context,outcome=outcome,incident=incident,finding=finding,response=response,url=url,source_type=kind,records_gap=gap,checked='2026-10-07')
cases=[
case('matthew-leahy','Matthew Leahy','20','Man','Psychosis service; detained at the Linden Centre','Death','Died on 15 November 2012, eight days after admission.','PHSO identified inadequate risk management and observations, a care plan completed after death, and inadequate action on his report of rape.','The trust initially described care as good. PHSO later found serious failures and sought an action plan.',PHSO,'Ombudsman finding', 'His report of rape is recorded; its occurrence is not resolved by this summary. The full family testimony and the institutional findings must both be read.'),
case('mr-r','Mr R','20','Man','Tentative ADHD and dissocial personality disorder diagnoses; Linden Centre','Death','Died during an inpatient admission in December 2008.','PHSO found missed opportunities to reduce suicide risk, inadequate medication monitoring, ward-leave risk assessment and care planning.','An internal investigation and inquest preceded the ombudsman investigation. The family experienced continuing injustice from deficient care.',PHSO,'Ombudsman finding'),
case('oliver-winson','Oliver Winson','33','Man','Adult ADHD assessment waiting list; substance misuse services','Death','Died from cocaine toxicity on 10 June 2024 after four years on the ADHD waiting list.','The coroner raised national concern about high-risk people awaiting ADHD assessment without treatment or monitoring. Additional funding had not significantly reduced his wait.','The 20 December 2024 report required a response from NHS England, with actions and a timetable or an explanation for no action.','https://www.judiciary.uk/prevention-of-future-death-reports/oliver-winson-prevention-of-future-deaths-report/'),
case('matthew-caseby','Matthew Caseby','Age not stated in the reviewed report extract','Man','Detained mental health inpatient; Woodbourne Priory','Death','Died after leaving the hospital courtyard during his admission in September 2020.','The inquest found neglect contributed to death. The report identified inadequate risk assessment, documentation and courtyard security, including missed learning from previous escapes.','CQC reported a guilty plea and a total payment of £693,852 in March 2024. A provider response is published with the coroner report.','https://www.judiciary.uk/prevention-of-future-death-reports/matthew-caseby-prevention-of-future-deaths-report/'),
case('connor-sparrowhawk','Connor Sparrowhawk','18','Boy','Autism, learning disabilities and epilepsy; Southern Health assessment unit','Death','Drowned following an epileptic seizure while bathing alone in 2013.','INQUEST records an inquest finding that neglect contributed to death and an independent investigation finding that the death was preventable, with failures in epilepsy management.','The unit closed. His family pursued the failures in care and communication.','https://history.inquest.org.uk/case-profiles/connor-sparrowhawk/','INQUEST case archive reporting formal findings'),
case('jennifer-chalkley','Jennifer Chalkley','17','Girl','ADHD and autism; education, health and multi-agency support','Death','The 2024 inquest concluded suicide.','The coroner recorded failures to communicate needs and coordinate support. A mistaken belief that schools first had to spend £6,000 was delaying statutory needs assessments.','The report acknowledged some concerns had been addressed and called for action on the remaining assessment barrier.','https://www.judiciary.uk/prevention-of-future-death-reports/jennifer-chalkley-prevention-of-future-deaths-report/'),
case('joshua-weavers','Joshua Weavers','17','Boy','Suicidal distress; autism assessment and therapy waiting lists','Death','Died by suicide on 4 March 2021 while still waiting for therapy.','Therapy stopped when a therapist left. Further intervention was deferred during a 22-month autism assessment process. The coroner raised national concerns about long waits and monitoring.','Reports were sent to NHS England, the ICB and the council. Local assessment and monitoring plans still needed commissioning input at the inquest.','https://www.judiciary.uk/prevention-of-future-death-reports/joshua-weavers-prevention-of-future-deaths-report/'),
case('molly-ann-sergeant','Molly-Ann Sergeant','17','Girl','Depression, self-harm and autism diagnosis; discharge after detention','Death','Died by suicide on 16 October 2020 following discharge in August.','The coroner recorded failures in requested social-care assessments and coordinated aftercare that contributed to death. Statutory confusion delayed reopening the case.','The report sought action on diagnosis, joined-up assessment and aftercare responsibilities.','https://www.judiciary.uk/prevention-of-future-death-reports/molly-ann-sergeant-prevention-of-future-deaths-report/'),
case('henry-grierson','Henry Grierson','17','Boy','CAMHS, Recovery Steps and college safeguarding','Death','Died in April 2024; the coroner issued a report on 4 November 2024.','The coroner was concerned that the college lacked current information after treatment and support ended, and that communication between agencies had not been maintained.','A formal response was required. The public report redacts its recipient and refers to a separate narrative conclusion.','https://www.judiciary.uk/prevention-of-future-death-reports/henry-grierson-prevention-of-future-deaths-report/',gap='The recipient is redacted. The separate narrative conclusion is not reproduced here; these limits do not establish why other records are unavailable.'),
case('beth','Beth / Bethany','17 when the case became public','Girl','Autistic looked-after child; St Andrew’s Healthcare','Serious harm','Prolonged seclusion and restrictive care; this is a living person’s case, not a death record.','The 2019 review found unmet needs, harmful restriction, weak safeguarding, poor regulatory follow-up and urgent actions with little impact.','NHS England conducted the review for the Secretary of State. It proposed coordinated planning, human-rights scrutiny, community provision and escalation.',BETH,'Government-published independent review', 'Only an excerpt was published. DHSC explicitly cites confidentiality and privacy as reasons; the page does not recast that as proof of deliberate concealment.'),
case('amy-el-keria','Amy El-Keria','14','Girl','Complex mental ill health; NHS-funded Priory children’s hospital','Death','Died by suicide while an inpatient. INQUEST records repeated restraint and sedative injections.','INQUEST records an inquest finding that neglect contributed to death and a guilty plea to health and safety breaches.','The Priory was fined £300,000. Her mother Tania campaigned for accountability; Amy’s sister continued after Tania’s death.','https://history.inquest.org.uk/case-profiles/amy-el-keria/','INQUEST case archive reporting formal findings'),
case('charlie-millers','Charlie Millers','17','Transgender boy','ADHD; suspected autism; Junction 17 children’s inpatient unit','Death','Died after a self-harm incident following return from home leave.','INQUEST records a 2024 jury conclusion that he did not intend to die, alongside failures in inter-service engagement and family support.','His mother Samantha continues to campaign. The archive links his pen portrait and the April 2024 prevention report.','https://history.inquest.org.uk/case-profiles/charlie-millers/','INQUEST case archive reporting formal findings'),
case('colette-mcculloch','Colette McCulloch','35','Woman','Autism diagnosed in adulthood; anorexia, anxiety and OCD; Pathway House','Death','Died after being struck by a lorry in July 2016 while missing from her placement.','INQUEST records a full inquest, secured after a legal battle, which identified an avoidable tragedy and multiple care-home failures.','Her parents Andy and Amanda published a memoir and spoke publicly about the fight to secure scrutiny.','https://history.inquest.org.uk/case-profiles/colette-mcculloch/','INQUEST case archive reporting formal findings')
]
OUT=S/'accountability/uk'; OUT.mkdir(parents=True,exist_ok=True)
(OUT/'cases').mkdir(exist_ok=True)
(OUT/'cases/cases.json').write_text(json.dumps(cases,indent=2,ensure_ascii=False)+'\n')
with (OUT/'cases/cases.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(cases[0]));w.writeheader();w.writerows(cases)
def page(title,desc,body,slug,extra=''):
 depth=len(slug.strip('/').split('/'));prefix='../'*depth
 return f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} — MJB ADHD</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="https://mjb-adhd.org.uk/{slug}"><link rel="stylesheet" href="/css/core.css"><link rel="stylesheet" href="/css/sleek.css"><link rel="stylesheet" href="/css/accountability.css"><link rel="icon" href="/assets/mjb-emblem.jpg"></head>
<body data-page="accountability-uk" data-depth="{depth}"><a class="skip-link" href="#main-content">Skip to content</a><header class="top" id="site-header"><nav aria-label="Main"><a href="/">Home</a> · <a href="/guide/">Guidebook</a> · <a href="/accountability/uk/">Accountability</a></nav></header><main class="wrap accountability-page" id="main-content"><nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/accountability/uk/">UK accountability</a></nav><p class="kicker">Reviewed 7 October 2026 · records beside the claims</p><h1>{html.escape(title)}</h1><p class="lede">{html.escape(desc)}</p>{body}</main><footer><div class="wrap"><p>Need help now? Immediate danger: <a href="tel:999">999</a>. Urgent help: <a href="tel:111">111</a>. Samaritans: <a href="tel:116123">116 123</a>.</p><a href="/contact/">Corrections and source submissions</a> · <a href="/accountability/">Matthew Bayliss’s personal record</a></div></footer><script defer src="/js/registry.js"></script><script defer src="/js/app.js"></script><script defer src="/js/interact.js"></script>{extra}</body></html>'''
hub=f'''
<p><strong>A warning, investigation or action plan is not the same as safer care.</strong> This section asks who owns a risk, what they must do, what they actually did, and what changed for the person affected.</p>
<nav class="section-links" aria-label="On this page"><a href="#roles">Who does what</a><a href="#findings">What investigators found</a><a href="#rules">Rules and safeguards</a><a href="#action">Ask for action</a><a href="#patterns">Recurring failures</a><a href="cases/">People and case records</a></nav>
<aside class="note"><strong>UK scope, England detail.</strong> CQC, PHSO and ICB routes below concern England. For other nations: {a('https://www.spso.org.uk/spso','Scotland: SPSO')}; {a('https://www.ombudsman.wales/fact-sheets/health-nhs-complaints-general-information/','Wales: Public Services Ombudsman')}; {a('https://www.nipso.org.uk/make-complaint/how-we-deal-your-complaint','Northern Ireland: NIPSO')}. Do not send a complaint to the wrong national body.</aside>
<section id="roles"><h2>Who does what — and what to ask them for</h2><p>Keep an immediate care request separate from the investigation of past failures. A complaints process does not itself deliver an appointment or prescribing decision.</p><div class="table-scroll" role="region" aria-label="Accountability responsibilities" tabindex="0"><table><caption>England: operational responsibility and scrutiny</caption><thead><tr><th>Body</th><th>Role</th><th>Concrete request</th></tr></thead><tbody>
<tr><th>Provider / treating team</th><td>Clinical assessment, treatment decisions, care planning and responding to safety concerns.</td><td>Named clinical owner, next decision date and an interim safety plan.</td></tr>
<tr><th>Integrated care board</th><td>Local commissioning and relevant NHS complaints routes.</td><td>Identify the commissioned pathway and resolve an access or ownership gap. {a(COMPLAINT,'NHS England routing guidance')}</td></tr>
<tr><th>NHS England</th><td>National NHS functions and complaints within its remit; local service complaints usually belong with the provider or ICB.</td><td>Identify its relevant function and what it will do, rather than treating it as a universal complaints destination.</td></tr>
<tr><th>CQC</th><td>Provider regulation, inspection and enforcement.</td><td>Assess a documented safety pattern against standards. CQC has powers beyond warning letters, including restrictions and cancellation. {a('https://www.cqc.org.uk/guidance-regulation/providers/enforcement/enforcement-policy/protecting-people-using-services-forcing-improvement','Enforcement policy')}</td></tr>
<tr><th>PHSO</th><td>Independent investigation of unresolved NHS England complaints, findings and recommended redress.</td><td>Investigate the failure and resulting injustice; track implementation. It can report non-compliance to Parliament. {a('https://www.ombudsman.org.uk/handling-complaint/information-organisations-we-investigate/putting-things-right','Putting things right')}</td></tr>
<tr><th>Local authority safeguarding</th><td>Care Act enquiries where the statutory adult safeguarding criteria are met.</td><td>Assess ongoing abuse or neglect and protection needs. {a('https://www.legislation.gov.uk/ukpga/2014/23/section/42','Section 42')}</td></tr>
<tr><th>HSSIB</th><td>Independent safety investigations and system recommendations.</td><td>Use its findings to challenge recurring system risks. A safety recommendation is distinct from an enforcement requirement.</td></tr>
<tr><th>Coroner / public inquiry</th><td>Investigating deaths, identifying prevention concerns or wider system failures.</td><td>Check the report, recipient, reply and evidence of implementation. {a('https://www.judiciary.uk/prevention-of-future-death-reports/oliver-winson-prevention-of-future-deaths-report/','Example PFD and response duty')}</td></tr>
</tbody></table></div><p>Professional regulation, criminal investigation and a legal remedy are additional, separate routes. A service complaint does not determine every question of professional misconduct, crime or legal liability. Get the correct specialist route identified in writing.</p></section>
<section id="findings"><h2>What the investigators themselves say</h2>
<article><h3>CQC: people become more ill while waiting</h3><p>CQC’s 2024/25 Mental Health Act report is accompanied by a warning about prolonged waits and deterioration. That connects access failure with safety, rather than treating waiting as neutral administration.</p><p>{a(CQC,'Read the report')} · {a('https://www.cqc.org.uk/press-release/people-waiting-too-long-mental-health-care-and-becoming-more-ill-while-they-wait-cqc','CQC’s statement')}</p></article>
<article><h3>PHSO: the response can compound the original harm</h3><p>In Matthew Leahy’s case, PHSO found significant care failures, inadequate investigation and a lack of openness with his family. The response itself added distress. Read the findings alongside the earlier institutional assessment of care.</p><p>{a(PHSO,'PHSO: Missed opportunities')} · <a href="cases/#matthew-leahy">Matthew’s record</a></p></article>
<article><h3>HSSIB: responsibility falls between organisations</h3><p>The May 2025 mental health overview found unclear responsibility across health, social care and education, especially during transitions. It identified continued use of outdated suicide-risk categories and weaknesses in learning and safety culture.</p><p>{a(HSSIB,'Read the national investigation')}</p></article>
<article><h3>Recommendations without implementation</h3><p>A cross-system HSSIB report found weak monitoring of recommendations and proposed a shared repository, oversight and escalation. Its contributors included CQC, NHS England, PHSO, DHSC and safety experts. These are acknowledged failures in the machinery for improvement.</p><p>{a(RECS,'Recommendations but no action')}</p></article>
<article><h3>Beth’s review: oversight activity, little effective action</h3><p>The government-published review identified unmet needs, restrictive care, poor safeguarding and weak follow-up of regulatory and urgent actions. It explicitly described a system needing fundamental change.</p><p>{a(BETH,'Read the published review excerpt')} · <a href="cases/#beth">Beth’s record</a></p></article>
</section>
<section id="rules"><h2>Rules intended to stop the same failures</h2><p>The existence of a rule is only the start. Ask for the policy used, the decision record, the action owner and evidence that the risk was reduced.</p><div class="table-scroll" role="region" aria-label="Safeguards and accountability" tabindex="0"><table><caption>What the safeguard addresses</caption><thead><tr><th>Rule or framework</th><th>Problem it addresses</th><th>What to request</th></tr></thead><tbody>
<tr><th>CQC fundamental standards</th><td>Person-centred care, dignity, consent, safety, safeguarding, complaints, governance and candour (Regulations 9–13, 16–17 and 20).</td><td>Which standard was applied and what corrective action was taken. {a(REGS,'Official regulations guide')}</td></tr>
<tr><th>Duty of candour</th><td>Openness and the prescribed response to a qualifying notifiable safety incident.</td><td>The incident assessment and reasons if the specific notification duty is said not to apply. Not every disputed decision automatically meets that threshold. {a('https://www.cqc.org.uk/guidance-providers/all-services/regulation-20-duty-candour','Regulation 20 guidance')}</td></tr>
<tr><th>Equality Act 2010</th><td>Substantial disadvantage faced by disabled people using services.</td><td>Reasonable adjustments recorded and implemented: accessible communication, support and a usable process. {a('https://www.legislation.gov.uk/ukpga/2010/15/notes/division/3/16/19','Service-provider adjustment duty')}</td></tr>
<tr><th>Care Act 2014, section 42</th><td>Abuse or neglect involving an adult with care/support needs who cannot protect themselves because of those needs.</td><td>The safeguarding assessment, protection actions and responsible agency. {a('https://www.legislation.gov.uk/ukpga/2014/23/section/42','Read the statutory criteria')}</td></tr>
<tr><th>NHS complaints regulations 2009</th><td>Proper investigation, a written outcome and action after a complaint.</td><td>Agreed response arrangements and an explanation if delayed. The six-month provision requires notification/explanation if no response; it is not permission to leave urgent care unresolved. {a('https://www.legislation.gov.uk/uksi/2009/309/regulation/14','Regulation 14')}</td></tr>
<tr><th>Patient Safety Incident Response Framework</th><td>Learning from incidents, with meaningful involvement of affected people.</td><td>The chosen learning response, family involvement and tracked improvement actions. {a('https://www.england.nhs.uk/patient-safety/patient-safety-insight/incident-response-framework/','NHS England framework')}</td></tr>
<tr><th>Coroners’ prevention reports</th><td>Risks identified after a death that require action to prevent recurrence.</td><td>The required reply, normally within 56 days, action timetable and implementation evidence. A reply is not proof that the action worked.</td></tr>
<tr><th>Human Rights Act 1998</th><td>Rights including life, freedom from inhuman or degrading treatment, liberty and private/family life.</td><td>Identify the relevant right, protective action and review route. A legal breach requires case-specific analysis. {a('https://www.legislation.gov.uk/ukpga/1998/42/schedule/1','Convention rights')}</td></tr>
<tr><th>Section 117 aftercare</th><td>Free aftercare for eligible people following specified forms of mental-health detention.</td><td>A jointly owned aftercare plan and provision based on assessed needs. {a('https://www.nhs.uk/social-care-and-support/care-after-a-hospital-stay/mental-health-aftercare/','NHS aftercare guide')}</td></tr>
<tr><th>Mental Health Act and reform</th><td>Detention, safeguards and aftercare obligations.</td><td>Identify the provision actually in force and applicable to the person. The 2025 Act’s reforms have commencement provisions; Royal Assent does not bring every reform into operation at once. {a('https://www.legislation.gov.uk/ukpga/2025/33/section/56','Commencement')} · {a('https://www.legislation.gov.uk/uksi/2026/385/contents/made','First commencement regulations')}</td></tr>
</tbody></table></div><p><a href="/rights/overview/">Medical rights and access</a> · <a href="/sources/">Source documents</a></p></section>
<section id="action"><h2>Turn an acknowledgment into an accountable action</h2><p>Ask for five things in one short message. Save the reply and compare it with what actually happens.</p><blockquote><p>Please identify the person responsible for the next care decision, the decision to be made, the date it will be made, the interim plan for managing the known risk, and who will verify that the agreed action has happened. If your organisation is not responsible, identify the receiving service and confirm that it has accepted responsibility.</p></blockquote><p><a href="/guide/index.html#/n/no-prescriber">No prescriber: the next request</a> · <a href="/support/when-help-doesnt-come/">Keep a usable evidence record</a></p></section>
<section id="patterns"><h2>The failures that recur</h2><p><strong>Risk is recognised, but ownership and effective action are missing.</strong> The records above repeatedly show delayed access, interrupted care, poor handovers, unmet physical and sensory needs, excluded families, insufficient safeguarding and weak follow-up. The linked cases show what those failures cost people.</p><p>HSSIB’s national findings, Beth’s review and the case records are evidence of these recurring problems. They do not establish that every service or every member of staff behaves this way. The test of accountability is concrete: who corrected the failure, by when, with what verification, and what happened when they did not?</p><p><strong>An apology, action plan or fine cannot be counted as a completed safety improvement without evidence of changed care.</strong> CQC’s prosecution over Matthew Caseby also shows that enforcement powers exist. The question is when they are used and whether they produce lasting protection.</p><p>{a('https://www.cqc.org.uk/press-release/priory-healthcare-limited-ordered-pay-ps693852-after-failing-provide-safe-care-and','Caseby prosecution')} · <a href="cases/">Read the non-personal case register</a> · <a href="/accountability/">Read Matthew Bayliss’s separate personal account</a></p></section>
'''
(OUT/'index.html').write_text(page('UK mental health care accountability','How responsibility, complaints, regulation and safety investigations are supposed to work — and where official records show they failed.',hub,'accountability/uk/'))
cards=[]
for c in cases:
 e=lambda k:html.escape(str(c[k]))
 cards.append(f'''<article class="case-card" id="{e('id')}" data-case data-outcome="{e('outcome')}" data-search="{html.escape(' '.join(str(v) for v in c.values()).lower())}"><h2>{e('name')}</h2><p class="case-kind">{e('outcome')} · {e('source_type')}</p><dl><dt>Age</dt><dd>{e('age')}</dd><dt>Gender / source description</dt><dd>{e('gender')}</dd><dt>Care context</dt><dd>{e('context')}</dd></dl><p>{e('incident')}</p><details><summary>Findings, response and records</summary><h3>What the reviewed evidence establishes</h3><p>{e('finding')}</p><h3>Response and accountability</h3><p>{e('response')}</p><h3>What the record still does not answer</h3><p>{e('records_gap')}</p><p>{a(c['url'],'Read the source and full account')}</p>{'<p><a href="../matthew-leahy/">Family testimony and the institutional response</a></p>' if c['id']=='matthew-leahy' else ''}</details></article>''')
register=f'''<p><strong>13 reviewed records: 12 deaths and one serious-harm case.</strong> Every entry identifies its source type. This is an expanding register, not a national death count. INQUEST entries are attributed to its case archive; they are not presented as independently re-examined court files.</p><p>Content includes death, sexual-assault reports, restraint and seclusion. Descriptions avoid procedural detail. Read at your own pace.</p><div class="case-controls"><label for="case-search">Find a person, condition, service or failure<input id="case-search" type="search" autocomplete="off" placeholder="For example: autism, aftercare, Matthew"></label><label for="case-outcome">Outcome<select id="case-outcome"><option value="">All records</option><option>Death</option><option>Serious harm</option></select></label></div><p id="case-count" role="status" aria-live="polite">13 records shown</p><p><a href="cases.csv" download>Download the register as CSV</a> · <a href="cases.json" download>Download source-linked JSON</a></p><div class="case-grid">{''.join(cards)}</div><section><h2>Voices and the wider record</h2><p>{a(LAMP,'Matthew Leahy: official family testimony and video')} · {a('https://lampardinquiry.org.uk/evidence/','Lampard Inquiry evidence directory')} · {a('https://www.judiciary.uk/prevention-of-future-death-reports/','Coroners’ reports and published responses')} · {a('https://history.inquest.org.uk/case-profiles/','INQUEST case archive')}</p><p>Records not obtained or not published are labelled by that precise status. We identify refusal, redaction, withheld material or deliberate concealment only where the reviewed evidence supports it. Not knowing a fact does not invalidate a person’s testimony.</p></section>'''
(OUT/'cases/index.html').write_text(page('People harmed: the case register','People, care contexts, documented failures and responses — separate from Matthew Bayliss’s personal case.',register,'accountability/uk/cases/','<script defer src="/js/accountability.js"></script>'))
(OUT/'matthew-leahy').mkdir(exist_ok=True)
detail=f'''<p>Matthew Leahy was 20. He died on 15 November 2012 while an inpatient at the Linden Centre. His mother’s public statement remembers a compassionate young man who loved the outdoors and had rescued two women from drowning. It also describes the lasting trauma of his death and the institutions’ response.</p><section><h2>His mother’s words</h2><blockquote><p>“I am Matthew's mum. I bear witness for him.”</p></blockquote><p>Melanie Leahy, public commemorative statement, pages 2–3. She records the doctor’s call as:</p><blockquote><p>“Matthews’ been found hanging it doesn’t look good”.</p></blockquote><p>She says she subsequently learned that he had already been dead for over an hour, and describes the resulting loss of trust and absence of compassion. This is her attributed testimony, not a finding invented by this website.</p><p>{a(STATEMENT,'Read her full statement')} · {a(LAMP,'Watch the official commemorative testimony')}</p></section><section><h2>What the institutional investigation found</h2><p>PHSO found failures in care planning, observations, risk management and physical care. It found an inadequate response to Matthew’s report of rape and serious problems with the investigation and openness to his family. A fuller care plan had been prepared after his death; disciplinary and professional-regulatory referrals followed.</p><p>The trust’s earlier investigation described care as good. PHSO’s later findings expose why that assurance was inadequate. The documented response sought further action and oversight; a promise of improvement is not proof of completed change.</p><p>{a(PHSO,'Read the findings in full')}</p></section><section><h2>Original calls and fuller evidence</h2><p>The reviewed commemorative statement contains his mother’s account of the doctor’s call. It is not an authenticated recording or verbatim transcript of a call made by Matthew. His words must not be reconstructed from summaries.</p><p>{a('https://lampardinquiry.org.uk/evidence/hearing-day-33-evidence/','The Inquiry’s fuller Melanie Leahy witness-statement record')} provides a route to the wider evidence. Any future audio extract will need its original recording, exact words and source location.</p></section><p><a href="../cases/#matthew-leahy">Back to Matthew’s register entry</a> · <a href="../#patterns">Recurring system failures</a></p>'''
(OUT/'matthew-leahy/index.html').write_text(page('Matthew Leahy: testimony and response','A family’s account alongside the ombudsman’s findings, with the original sources available to read and watch.',detail,'accountability/uk/matthew-leahy/'))
print(f'Built accountability hub, testimony page and {len(cases)} case records.')
